apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tc1lr7d78-go 
  janus-idp.io/tekton: tc1lr7d78-go
  backstage.io/kubernetes-id: tc1lr7d78-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tc1lr7d78-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml