apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tc1lr7d78-go
  janus-idp.io/tekton: tc1lr7d78-go
  backstage.io/kubernetes-id: tc1lr7d78-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tc1lr7d78-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
