apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tc1lr7d78-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tc1lr7d78-go 
  name: tc1lr7d78-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tc1lr7d78-go 
